// <auto-generated />
using CodeFirstOrnek;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstOrnek.Migrations
{
    [DbContext(typeof(UygulamaContextDb))]
    [Migration("20231123113629_ILK")]
    partial class ILK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstOrnek.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("KatEttigiMesafe")
                        .HasColumnType("real");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arabalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KatEttigiMesafe = 10000f,
                            Marka = "Toyota",
                            Model = "Corolla",
                            Renk = "Siyah"
                        },
                        new
                        {
                            Id = 2,
                            KatEttigiMesafe = 8000f,
                            Marka = "Honda",
                            Model = "Civic",
                            Renk = "Beyaz"
                        },
                        new
                        {
                            Id = 3,
                            KatEttigiMesafe = 12000f,
                            Marka = "Ford",
                            Model = "Focus",
                            Renk = "Mavi"
                        },
                        new
                        {
                            Id = 4,
                            KatEttigiMesafe = 15000f,
                            Marka = "Volkswagen",
                            Model = "Golf",
                            Renk = "Kırmızı"
                        },
                        new
                        {
                            Id = 5,
                            KatEttigiMesafe = 9000f,
                            Marka = "Renault",
                            Model = "Megane",
                            Renk = "Gri"
                        },
                        new
                        {
                            Id = 6,
                            KatEttigiMesafe = 11000f,
                            Marka = "Chevrolet",
                            Model = "Cruze",
                            Renk = "Sarı"
                        },
                        new
                        {
                            Id = 7,
                            KatEttigiMesafe = 13000f,
                            Marka = "Hyundai",
                            Model = "Elantra",
                            Renk = "Yeşil"
                        },
                        new
                        {
                            Id = 8,
                            KatEttigiMesafe = 10000f,
                            Marka = "Nissan",
                            Model = "Altima",
                            Renk = "Turuncu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
