// <auto-generated />
using CodeFirstOrnek;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstOrnek.Migrations
{
    [DbContext(typeof(UygulamaContextDb))]
    partial class UygulamaContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.Property<int>("ArabalarId")
                        .HasColumnType("int");

                    b.Property<int>("MuhendisListesiId")
                        .HasColumnType("int");

                    b.HasKey("ArabalarId", "MuhendisListesiId");

                    b.HasIndex("MuhendisListesiId");

                    b.ToTable("ArabaMuhendis", (string)null);
                });

            modelBuilder.Entity("CodeFirstOrnek.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("KatEttigiMesafe")
                        .HasColumnType("real");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlakaId")
                        .HasColumnType("int");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SahipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlakaId")
                        .IsUnique();

                    b.HasIndex("SahipId");

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("CodeFirstOrnek.Muhendis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muhendisler");
                });

            modelBuilder.Entity("CodeFirstOrnek.Plaka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlakaKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plakalar");
                });

            modelBuilder.Entity("CodeFirstOrnek.Sahip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sahipler");
                });

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.HasOne("CodeFirstOrnek.Araba", null)
                        .WithMany()
                        .HasForeignKey("ArabalarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstOrnek.Muhendis", null)
                        .WithMany()
                        .HasForeignKey("MuhendisListesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFirstOrnek.Araba", b =>
                {
                    b.HasOne("CodeFirstOrnek.Plaka", "Plaka")
                        .WithOne("araba")
                        .HasForeignKey("CodeFirstOrnek.Araba", "PlakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstOrnek.Sahip", "Sahip")
                        .WithMany("KisininArabalari")
                        .HasForeignKey("SahipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plaka");

                    b.Navigation("Sahip");
                });

            modelBuilder.Entity("CodeFirstOrnek.Plaka", b =>
                {
                    b.Navigation("araba")
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFirstOrnek.Sahip", b =>
                {
                    b.Navigation("KisininArabalari");
                });
#pragma warning restore 612, 618
        }
    }
}
